server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          enabled: true
        routes:
          - id: auth-service-route
            uri: lb://auth-service
          - predicates:
            - Path=/auth/**