server:
  port: 9002

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order_service_db
    username: mrlii
    password: postgresdev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

topic:
  order-created: order-created-topic
  order-updated: order-updated-topic
  order-deleted: order-deleted-topic
  name: "order-events"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/